name: neuro_hub
description: A Flutter app to manage devices part of the Neuro family ecosystem.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  generate: true
  image_path: "assets/neurostore_logo.png"

  windows:
    icon: assets/neurostore_logo.png
    generate: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/